#!/bin/bash

help () {
	echo
	echo "[*] For delivery ratio statistics run: "
	echo "[*] ./simu -traffic -interv <seconds> "
	echo
	echo
	echo "[*] For duty cycle statistics run:"
	echo "[*] ./simu -dutycycle -BO <value> "
	echo
	exit
}

if [ "$#" -lt 3 ]
then
	help
fi



if [ "$1" == "-traffic" ] && [ "$2" == "-interv" ]; then
	echo "[+] Running simulation"
	echo
	ns wpan_demo2.tcl -inter_pkt_interv $3 -BO 4 &> /dev/null
	echo "[+] Data analysis"
	echo	
	cat wpan_demo2.tr | awk -f delivery-ratio.awk
elif [ "$1" == "-dutycycle" ] && [ "$2" == "-BO" ]; then
	echo "[+] Running simulation"
	echo
	ns wpan_demo2.tcl -inter_pkt_interv 0.2 -BO $3 &> /dev/null
	echo "[+] Data analysis"	
	echo	
	cat wpan_demo2.tr | awk -f duty-cycle.awk
else
	help
fi


